config/routes.rb
Ruby::Application.routes.draw do
  resources :story_statuses

  resources :story_comments

  resources :stories

  get "home/index"

 resources :sessions
 resources :users
get 'register' => 'users#new', :as => 'register'
get 'login' => 'sessions#new', :as => 'login'
get 'logout' => 'sessions#destroy', :as => 'logout' 
post 'sessions/new'=>'sessions#create', :as =>'session_new'

   root :to => 'stories#index'

end

app/models/story_comment.rb
class StoryComment < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
  validates :comment,:presence   => true,
                     :length     => { :within => 10..255 }
                     
end

app/controllers/story_comments_controller.rb
class StoryCommentsController < ApplicationController
  # GET /story_comments
  # GET /story_comments.json
  def index
    @story_comments = StoryComment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @story_comments }
    end
  end

  # GET /story_comments/1
  # GET /story_comments/1.json
  def show
    @story_comment = StoryComment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @story_comment }
    end
  end

  # GET /story_comments/new
  # GET /story_comments/new.json
  def new
    @story_comment = StoryComment.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @story_comment }
    end
  end

  
  # POST /story_comments
  # POST /story_comments.json
  def create
    @story_comment = StoryComment.new(params[:story_comment])
    @story_comment.user_id = self.current_user.id
    @story = Story.find(params[:story_comment][:story_id])
    @story_comment.story_id = @story.id
    respond_to do |format|
      if @story_comment.save
        format.html { redirect_to @story, :notice => 'Story comment was successfully created.' }
        format.json { render :json => @story_comment, :status => :created, :location => @story_comment }
      else
        format.html { render @story , :notice => 'error' }
        format.json { render :json => @story_comment.errors, :status => :unprocessable_entity }
      end
    end
  end


  # DELETE /story_comments/1
  # DELETE /story_comments/1.json
  def destroy
    @story_comment = StoryComment.find(params[:id])
    @story_comment.destroy

    respond_to do |format|
      format.html { redirect_to story_comments_url }
      format.json { head :ok }
    end
  end
end

app/helpers/story_comments_helper.rb
module StoryCommentsHelper
end

app/views/story_comments/_form.html.erb
<%= form_for(@story_comment) do |f| %>
  <% if @story_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story_comment.errors.count, "error") %> prohibited this story_comment from being saved:</h2>

      <ul>
      <% @story_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment, :cols => 500, :rows => 20 %>
  </div>
    <%= f.hidden_field :story_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/story_comments/edit.html.erb
<h1>Editing story_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @story_comment %> |
<%= link_to 'Back', story_comments_path %>

app/views/story_comments/index.html.erb
<h1>Listing story_comments</h1>

<table>
  <tr>
    <th>Comment</th>
    <th>Text</th>
    <th>Story</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @story_comments.each do |story_comment| %>
  <tr>
    <td><%= story_comment.comment %></td>
    <td><%= story_comment.text %></td>
    <td><%= story_comment.story %></td>
    <td><%= story_comment.user %></td>
    <td><%= link_to 'Show', story_comment %></td>
    <td><%= link_to 'Edit', edit_story_comment_path(story_comment) %></td>
    <td><%= link_to 'Destroy', story_comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Story comment', new_story_comment_path %>

app/views/story_comments/new.html.erb
<h1>New story_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', story_comments_path %>

app/views/story_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @story_comment.comment %>
</p>

<p>
  <b>Text:</b>
  <%= @story_comment.text %>
</p>

<p>
  <b>Story:</b>
  <%= @story_comment.story %>
</p>

<p>
  <b>User:</b>
  <%= @story_comment.user %>
</p>


<%= link_to 'Edit', edit_story_comment_path(@story_comment) %> |
<%= link_to 'Back', story_comments_path %>