config/routes.rb
Ruby::Application.routes.draw do
  resources :story_statuses

  resources :story_comments

  resources :stories

  get "home/index"

 resources :sessions
 resources :users
get 'register' => 'users#new', :as => 'register'
get 'login' => 'sessions#new', :as => 'login'
get 'logout' => 'sessions#destroy', :as => 'logout' 
post 'sessions/new'=>'sessions#create', :as =>'session_new'

   root :to => 'stories#index'

end

app/controllers/story_statuses_controller.rb
class StoryStatusesController < ApplicationController
  # GET /story_statuses
  # GET /story_statuses.json
  def index
    @story_statuses = StoryStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @story_statuses }
    end
  end

  # GET /story_statuses/1
  # GET /story_statuses/1.json
  def show
    @story_status = StoryStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @story_status }
    end
  end

  # GET /story_statuses/new
  # GET /story_statuses/new.json
  def new
    @story_status = StoryStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @story_status }
    end
  end

  # GET /story_statuses/1/edit
  def edit
    @story_status = StoryStatus.find(params[:id])
  end

  # POST /story_statuses
  # POST /story_statuses.json
  def create
    @story_status = StoryStatus.new(params[:story_status])

    respond_to do |format|
      if @story_status.save
        format.html { redirect_to @story_status, :notice => 'Story status was successfully created.' }
        format.json { render :json => @story_status, :status => :created, :location => @story_status }
      else
        format.html { render :action => "new" }
        format.json { render :json => @story_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /story_statuses/1
  # PUT /story_statuses/1.json
  def update
    @story_status = StoryStatus.find(params[:id])

    respond_to do |format|
      if @story_status.update_attributes(params[:story_status])
        format.html { redirect_to @story_status, :notice => 'Story status was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @story_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /story_statuses/1
  # DELETE /story_statuses/1.json
  def destroy
    @story_status = StoryStatus.find(params[:id])
    @story_status.destroy

    respond_to do |format|
      format.html { redirect_to story_statuses_url }
      format.json { head :ok }
    end
  end
end

app/helpers/story_statuses_helper.rb
module StoryStatusesHelper
end

app/views/story_statuses/_form.html.erb
<%= form_for(@story_status) do |f| %>
  <% if @story_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story_status.errors.count, "error") %> prohibited this story_status from being saved:</h2>

      <ul>
      <% @story_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/story_statuses/edit.html.erb
<h1>Editing story_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @story_status %> |
<%= link_to 'Back', story_statuses_path %>

app/views/story_statuses/index.html.erb
<h1>Listing story_statuses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Story</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @story_statuses.each do |story_status| %>
  <tr>
    <td><%= story_status.name %></td>
    <td><%= story_status.story %></td>
    <td><%= link_to 'Show', story_status %></td>
    <td><%= link_to 'Edit', edit_story_status_path(story_status) %></td>
    <td><%= link_to 'Destroy', story_status, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Story status', new_story_status_path %>

app/views/story_statuses/new.html.erb
<h1>New story_status</h1>

<%= render 'form' %>

<%= link_to 'Back', story_statuses_path %>

app/views/story_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @story_status.name %>
</p>

<p>
  <b>Story:</b>
  <%= @story_status.story %>
</p>


<%= link_to 'Edit', edit_story_status_path(@story_status) %> |
<%= link_to 'Back', story_statuses_path %>