config/routes.rb
Ruby::Application.routes.draw do
  resources :story_statuses

  resources :story_comments

  resources :stories

  get "home/index"

 resources :sessions
 resources :users
get 'register' => 'users#new', :as => 'register'
get 'login' => 'sessions#new', :as => 'login'
get 'logout' => 'sessions#destroy', :as => 'logout' 
post 'sessions/new'=>'sessions#create', :as =>'session_new'

   root :to => 'stories#index'

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user 
  has_many :story_comments
  belongs_to :story_status
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json
  def index
    if params[:user] && params[:status]
      if params[:user]=='all' && params[:status]== 'all'
        @stories = Story.all  
      elsif params[:user]=='all'
         @stories = Story.find_all_by_story_status_id(params[:status])
      elsif  params[:status]== 'all'
         @stories = Story.find_all_by_user_id(params[:user])
      else
         @stories = Story.find_all_by_user_id_and_story_status_id(params[:status])
      end
    else
    @stories = Story.all  
    end
    @user = User.all
    @story_statuses = StoryStatus.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])
    @story_comment = StoryComment.new
    @story_comment.story_id = @story.id
    @story_comments = StoryComment.find_all_by_story_id(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new
    @story_statuses = StoryStatus.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
    @story_statuses = StoryStatus.all
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])
    @story.user_id = self.current_user.id
    #@StoryStatus = StoryStatus.find(1)
    @story.story_status_id = 1
    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, :notice => 'Story was successfully created.' }
        format.json { render :json => @story, :status => :created, :location => @story }
      else
        format.html { render :action => "new" }
        format.json { render :json => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])
    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, :notice => 'Story was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div><br />
  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text, :class=>"xxlarge"%>
  </div><br />


  <div class="actions">
    <%= f.submit :class=>"btn success"%>
  </div>
<% end %>

app/views/stories/_form_edit.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= @story.name %>
  </div><br/>
  <div class="field">
    <%= f.label :text %>
    <%= @story.text %>
  </div><br/>
  <div class="field">
    <%= f.label :story_status_id %>
    <%= f.select :story_status_id , options_from_collection_for_select(@story_statuses, "id", "name",@story.story_status_id)  %>
  </div><br/>

  <div class="actions">
    <%= f.submit :class=>"btn success"%>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form_edit' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', '/' %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>
<%= link_to 'New Story', new_story_path, :class=>"btn success" %>
<br/>   
<%= form_tag '/' do %>
<p><%= label_tag 'user' %>
<%= select_tag 'user', options_from_collection_for_select(@user, "id", "login")<< '<option value="all">All</option>'.html_safe %></p>
<p><%= label_tag 'status' %>
<%= select_tag 'status', options_from_collection_for_select(@story_statuses, "id", "name")<< '<option value="all">All</option>'.html_safe %></p>
<p><%= submit_tag 'Search', :class=>"btn info"%></p>
<% end -%>
<table class="bordered-table zebra-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Text</th>
    <th>State</th>
    <th>User</th>
    <th>Comment</th>
    <th></th>

  </tr>
   </thead>
   <tbody>
<% @stories.each do |story| %>
  <tr>
    <td><%= story.name %></td>
    <td><%= story.text %></td>
    <td><%= story.story_status ? story.story_status.name : '' %></td>
    <td><%= story.user.login %></td>
    <td><%= story.story_comments.count() %></td>
    <td><%= link_to 'Show', story %> 
    <%= link_to 'Edit', edit_story_path(story) %> 
    <%= link_to 'Destroy', story, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', '/' %>

app/views/stories/show.html.erb
<p>
  <b>Name:</b>
  <%= @story.name %>
</p>

<p>
  <b>Text:</b>
  <%= @story.text %>
</p>

<p>
  <b>State:</b>
  <%= @story.story_status ? @story.story_status.name : ''%>
</p>

<p>
  <b>User:</b>
  <%= @story.user.login %>
</p>
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', '/' %>

<h1>Listing story_comments</h1>

<table>
  <tr>
    <th>Comment</th>
    <th>User</th>
    <th></th>
  </tr>

<% @story_comments.each do |story_comment| %>
  <tr>
    <td><%= story_comment.comment %></td>
    <td><%= story_comment.user ? story_comment.user.login : '' %></td>
    <td><%=  if current_user.id == story_comment.user_id
  link_to 'Destroy', story_comment, :confirm => 'Are you sure?', :method => :delete 
             end%>
    </td>
  </tr>
<% end %>
</table>
<%= render 'story_comments/form' %>